### ISSUE TITLE
Stopped working with newest TT-RSS

### ISSUE THREAD

**Issue by Andyt8** [GregThib/ttrss-qrcodegen#1]
It looks like there where a change with newest TT-RSS. The plugin is still enabled, but the QR code icon is no longer displayed on articles.

**Comment by GregThib** [comment]
Hmmm, exact. As some more plugins (close_button, tweet, youls, shaarli).
Will investigate soon, when getting time.

Thank for report!

**Comment by Andyt8** [comment]
Great, thanks. Looking forward.

**Comment by GregThib** [comment]
Oh, I'm back. I supplied a question on [tt-rss forum](https://community.tt-rss.org/t/hook-article-button/5164) and @fox added a warning when plugins return malformed XML.
And so, I've [updated](https://github.com/GregThib/ttrss-qrcodegen/commit/de657545b3037f83cb7a40646f2a6a51652e00c2) this one.

FYI, if you have other plugins not running correctly, try to check if `function hook_article_button($line)` return correct HTML/XML code. Here, it missed to close the <img> tag.

**Comment by Andyt8** [comment]
Thank you for the the information and of' course for the new version.
